### ISSUE TITLE
Customize daemon port

### ISSUE THREAD

**Issue by ta1kt0me** [asonas/rspec-daemon#2]
Thank you for making this useful gem 🎉.
Currently the port is fixed to 3002, but I would like to change the daemon port to another port such as 13002 or 23002 if possible. Do you have any plans for using environment variables, patching rspec options, generating specific client scripts, etc.?

**Comment by asonas** [comment]
@ta1kt0me 
Hello 👋 
I have released v1.0.0 and can change the port. You can set it from environment variables or options.

https://rubygems.org/gems/rspec-daemon/versions/1.0.0

**Comment by ta1kt0me** [comment]
Thank you!
